* If an Exchange failed during routing the Exception that caused the failure is stored and accessible via the getException() method.:wq

